# Comando para levantar contenedor sin cache de imagenes:
# docker compose -f docker-compose.yml build --no-cache
# docker compose up -d
# docker compose -f <nombreArchivo>.yml up -d

version: '3'

networks:
  dnpap:
    name: dnpap
    driver: bridge

services:
  frontend:
    container_name: frontend
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - 8080:8080
    environment:
      - REACT_APP_AUTH_URL=http://34.125.176.205:5000/
    networks:
      - dnpap
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: 250M
        # Recusos dedicados, mantiene los recursos disponibles del host para el contenedor
        reservations:
          cpus: "0.1"
          memory: 128M
    env_file:
      - .env
