# Comando para levantar contenedor sin cache de imagenes:
# docker compose -f docker-compose.yml build --no-cache
# docker compose up -d
# docker compose -f <nombreArchivo>.yml up -d

version: '3'

networks:
  dnpap:
    name: dnpap
    driver: bridge

services:
  backend:
    image: backend-dev-i
    container_name: backend-dev-c
    hostname: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    networks:
      - dnpap
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - .env.dev

  frontend:
    image: frontend-dev-i
    container_name: frontend-dev-c
    hostname: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        - VITE_BACKEND_URL=https://backend.mspasdnpap.com
    networks:
      - dnpap
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend