# Comando para levantar contenedor sin cache de imagenes:
# docker compose -f docker-compose.yml build --no-cache
# docker compose up -d
# docker compose -f <nombreArchivo>.yml up -d

version: '3'

networks:
  dnpap:
    name: dnpap
    driver: bridge

services:
  backend:
    image: backend-prod-i
    container_name: backend-prod-c
    hostname: backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    networks:
      - dnpap
    ports:
      - 5000:5000
    env_file:
      - .env.prod

  frontend:
    image: frontend-prod-i
    container_name: frontend-prod-c
    hostname: frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        # La ip debe ser la del servidor donde se encuentra el backend (no localhost)
        - VITE_BACKEND_URL=http://64.23.135.40:5000
    networks:
      - dnpap
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  dnpap-mysql-db-prod: